### PR TITLE
Bug fix: view membership & member relationships profile page

### LINKED ISSUE #344: membership category for profile page doesn't show membership relationships [2]
example: https://www.littlesis.org/org/86757-Georgia_Chamber_of_Commerce?relationships=members

### PR DESCRIPTION
**Pull request by aepyornis**
resolves #344

### CODE REVIEW

File: spec/features/entity_page_spec.rb [hunk 1]
```diff
@@ -168,6 +168,32 @@ def should_visit_entity_page(url)
     end
   end
 
+  describe "Relationship Tab - with category Membership" do
```
Comment (aguestuser) [inline spec/features/entity_page_spec.rb]: you could probably delete the pending `describe "relationships tab" on line 197?

**Comment by aguestuser** [comment]
looks good! is there a reason why you didn't want me to review this? b/c submitted on a friday?

File: app/utility/sorted_links.rb [hunk 2]
```diff
@@ -27,6 +28,8 @@ class SortedLinks
     'government_positions' => 1,
     'in_the_office_positions' => 1,
     'staff' => 1,
+    'members' => 3,
```
Comment (aguestuser) [inline app/utility/sorted_links.rb]: lots of magic numbers here...
